package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import q4s.tutorials.mybatis.BaseEntity;

public class Employees extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEES.EMP_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long empId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEES.NICKNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEES.LNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String lname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEES.FNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String fname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEES.MNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String mname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEES.SKILL_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long skillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEES.EMAIL
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EMPLOYEES.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String stuff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table EMPLOYEES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Employees(Long empId, String nickname, String lname, String fname, String mname, Long skillId,
			String email) {
		this.empId = empId;
		this.nickname = nickname;
		this.lname = lname;
		this.fname = fname;
		this.mname = mname;
		this.skillId = skillId;
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Employees(Long empId, String nickname, String lname, String fname, String mname, Long skillId, String email,
			String stuff) {
		this.empId = empId;
		this.nickname = nickname;
		this.lname = lname;
		this.fname = fname;
		this.mname = mname;
		this.skillId = skillId;
		this.email = email;
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Employees() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEES.EMP_ID
	 * @return  the value of EMPLOYEES.EMP_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEES.EMP_ID
	 * @param empId  the value for EMPLOYEES.EMP_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEES.NICKNAME
	 * @return  the value of EMPLOYEES.NICKNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEES.NICKNAME
	 * @param nickname  the value for EMPLOYEES.NICKNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEES.LNAME
	 * @return  the value of EMPLOYEES.LNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getLname() {
		return lname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEES.LNAME
	 * @param lname  the value for EMPLOYEES.LNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setLname(String lname) {
		this.lname = lname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEES.FNAME
	 * @return  the value of EMPLOYEES.FNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getFname() {
		return fname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEES.FNAME
	 * @param fname  the value for EMPLOYEES.FNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setFname(String fname) {
		this.fname = fname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEES.MNAME
	 * @return  the value of EMPLOYEES.MNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getMname() {
		return mname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEES.MNAME
	 * @param mname  the value for EMPLOYEES.MNAME
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setMname(String mname) {
		this.mname = mname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEES.SKILL_ID
	 * @return  the value of EMPLOYEES.SKILL_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getSkillId() {
		return skillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEES.SKILL_ID
	 * @param skillId  the value for EMPLOYEES.SKILL_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setSkillId(Long skillId) {
		this.skillId = skillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEES.EMAIL
	 * @return  the value of EMPLOYEES.EMAIL
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEES.EMAIL
	 * @param email  the value for EMPLOYEES.EMAIL
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EMPLOYEES.STUFF
	 * @return  the value of EMPLOYEES.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getStuff() {
		return stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EMPLOYEES.STUFF
	 * @param stuff  the value for EMPLOYEES.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setStuff(String stuff) {
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", empId=").append(empId);
		sb.append(", nickname=").append(nickname);
		sb.append(", lname=").append(lname);
		sb.append(", fname=").append(fname);
		sb.append(", mname=").append(mname);
		sb.append(", skillId=").append(skillId);
		sb.append(", email=").append(email);
		sb.append(", stuff=").append(stuff);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Employees other = (Employees) that;
		return (this.getEmpId() == null ? other.getEmpId() == null : this.getEmpId().equals(other.getEmpId()))
				&& (this.getNickname() == null ? other.getNickname() == null
						: this.getNickname().equals(other.getNickname()))
				&& (this.getLname() == null ? other.getLname() == null : this.getLname().equals(other.getLname()))
				&& (this.getFname() == null ? other.getFname() == null : this.getFname().equals(other.getFname()))
				&& (this.getMname() == null ? other.getMname() == null : this.getMname().equals(other.getMname()))
				&& (this.getSkillId() == null ? other.getSkillId() == null
						: this.getSkillId().equals(other.getSkillId()))
				&& (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
				&& (this.getStuff() == null ? other.getStuff() == null : this.getStuff().equals(other.getStuff()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table EMPLOYEES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getEmpId() == null) ? 0 : getEmpId().hashCode());
		result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
		result = prime * result + ((getLname() == null) ? 0 : getLname().hashCode());
		result = prime * result + ((getFname() == null) ? 0 : getFname().hashCode());
		result = prime * result + ((getMname() == null) ? 0 : getMname().hashCode());
		result = prime * result + ((getSkillId() == null) ? 0 : getSkillId().hashCode());
		result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
		result = prime * result + ((getStuff() == null) ? 0 : getStuff().hashCode());
		return result;
	}
}