package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import q4s.tutorials.mybatis.BaseEntity;

public class Priorities extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRIORITIES.PRIORITY_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long priorityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRIORITIES.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRIORITIES.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PRIORITIES.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Priorities(Long priorityId, String code, String title, String description) {
		this.priorityId = priorityId;
		this.code = code;
		this.title = title;
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Priorities() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRIORITIES.PRIORITY_ID
	 * @return  the value of PRIORITIES.PRIORITY_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getPriorityId() {
		return priorityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRIORITIES.PRIORITY_ID
	 * @param priorityId  the value for PRIORITIES.PRIORITY_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setPriorityId(Long priorityId) {
		this.priorityId = priorityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRIORITIES.CODE
	 * @return  the value of PRIORITIES.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRIORITIES.CODE
	 * @param code  the value for PRIORITIES.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRIORITIES.TITLE
	 * @return  the value of PRIORITIES.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRIORITIES.TITLE
	 * @param title  the value for PRIORITIES.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PRIORITIES.DESCRIPTION
	 * @return  the value of PRIORITIES.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PRIORITIES.DESCRIPTION
	 * @param description  the value for PRIORITIES.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", priorityId=").append(priorityId);
		sb.append(", code=").append(code);
		sb.append(", title=").append(title);
		sb.append(", description=").append(description);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Priorities other = (Priorities) that;
		return (this.getPriorityId() == null ? other.getPriorityId() == null
				: this.getPriorityId().equals(other.getPriorityId()))
				&& (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getPriorityId() == null) ? 0 : getPriorityId().hashCode());
		result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		return result;
	}
}