package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import q4s.tutorials.mybatis.BaseEntity;

public class Projects extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROJECTS.PROJECT_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROJECTS.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROJECTS.MAJOR_VER
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Integer majorVer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROJECTS.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROJECTS.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROJECTS.STATE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long stateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PROJECTS.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String stuff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PROJECTS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECTS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Projects(Long projectId, String code, Integer majorVer, String title, String description, Long stateId) {
		this.projectId = projectId;
		this.code = code;
		this.majorVer = majorVer;
		this.title = title;
		this.description = description;
		this.stateId = stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECTS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Projects(Long projectId, String code, Integer majorVer, String title, String description, Long stateId,
			String stuff) {
		this.projectId = projectId;
		this.code = code;
		this.majorVer = majorVer;
		this.title = title;
		this.description = description;
		this.stateId = stateId;
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECTS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Projects() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROJECTS.PROJECT_ID
	 * @return  the value of PROJECTS.PROJECT_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROJECTS.PROJECT_ID
	 * @param projectId  the value for PROJECTS.PROJECT_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROJECTS.CODE
	 * @return  the value of PROJECTS.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROJECTS.CODE
	 * @param code  the value for PROJECTS.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROJECTS.MAJOR_VER
	 * @return  the value of PROJECTS.MAJOR_VER
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Integer getMajorVer() {
		return majorVer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROJECTS.MAJOR_VER
	 * @param majorVer  the value for PROJECTS.MAJOR_VER
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setMajorVer(Integer majorVer) {
		this.majorVer = majorVer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROJECTS.TITLE
	 * @return  the value of PROJECTS.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROJECTS.TITLE
	 * @param title  the value for PROJECTS.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROJECTS.DESCRIPTION
	 * @return  the value of PROJECTS.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROJECTS.DESCRIPTION
	 * @param description  the value for PROJECTS.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROJECTS.STATE_ID
	 * @return  the value of PROJECTS.STATE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROJECTS.STATE_ID
	 * @param stateId  the value for PROJECTS.STATE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setStateId(Long stateId) {
		this.stateId = stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PROJECTS.STUFF
	 * @return  the value of PROJECTS.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getStuff() {
		return stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PROJECTS.STUFF
	 * @param stuff  the value for PROJECTS.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setStuff(String stuff) {
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECTS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", projectId=").append(projectId);
		sb.append(", code=").append(code);
		sb.append(", majorVer=").append(majorVer);
		sb.append(", title=").append(title);
		sb.append(", description=").append(description);
		sb.append(", stateId=").append(stateId);
		sb.append(", stuff=").append(stuff);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECTS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Projects other = (Projects) that;
		return (this.getProjectId() == null ? other.getProjectId() == null
				: this.getProjectId().equals(other.getProjectId()))
				&& (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
				&& (this.getMajorVer() == null ? other.getMajorVer() == null
						: this.getMajorVer().equals(other.getMajorVer()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()))
				&& (this.getStateId() == null ? other.getStateId() == null
						: this.getStateId().equals(other.getStateId()))
				&& (this.getStuff() == null ? other.getStuff() == null : this.getStuff().equals(other.getStuff()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECTS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
		result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
		result = prime * result + ((getMajorVer() == null) ? 0 : getMajorVer().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		result = prime * result + ((getStateId() == null) ? 0 : getStateId().hashCode());
		result = prime * result + ((getStuff() == null) ? 0 : getStuff().hashCode());
		return result;
	}
}