package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import java.util.Date;
import q4s.tutorials.mybatis.BaseEntity;

public class Releases extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RELEASES.RELEASE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long releaseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RELEASES.REV_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long revId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RELEASES.RELEASE_VER
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Integer releaseVer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RELEASES.RELEASE_DATE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Date releaseDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column RELEASES.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String stuff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Releases(Long releaseId, Long revId, Integer releaseVer, Date releaseDate) {
		this.releaseId = releaseId;
		this.revId = revId;
		this.releaseVer = releaseVer;
		this.releaseDate = releaseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Releases(Long releaseId, Long revId, Integer releaseVer, Date releaseDate, String stuff) {
		this.releaseId = releaseId;
		this.revId = revId;
		this.releaseVer = releaseVer;
		this.releaseDate = releaseDate;
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Releases() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RELEASES.RELEASE_ID
	 * @return  the value of RELEASES.RELEASE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getReleaseId() {
		return releaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RELEASES.RELEASE_ID
	 * @param releaseId  the value for RELEASES.RELEASE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setReleaseId(Long releaseId) {
		this.releaseId = releaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RELEASES.REV_ID
	 * @return  the value of RELEASES.REV_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getRevId() {
		return revId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RELEASES.REV_ID
	 * @param revId  the value for RELEASES.REV_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setRevId(Long revId) {
		this.revId = revId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RELEASES.RELEASE_VER
	 * @return  the value of RELEASES.RELEASE_VER
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Integer getReleaseVer() {
		return releaseVer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RELEASES.RELEASE_VER
	 * @param releaseVer  the value for RELEASES.RELEASE_VER
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setReleaseVer(Integer releaseVer) {
		this.releaseVer = releaseVer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RELEASES.RELEASE_DATE
	 * @return  the value of RELEASES.RELEASE_DATE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Date getReleaseDate() {
		return releaseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RELEASES.RELEASE_DATE
	 * @param releaseDate  the value for RELEASES.RELEASE_DATE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column RELEASES.STUFF
	 * @return  the value of RELEASES.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getStuff() {
		return stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column RELEASES.STUFF
	 * @param stuff  the value for RELEASES.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setStuff(String stuff) {
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", releaseId=").append(releaseId);
		sb.append(", revId=").append(revId);
		sb.append(", releaseVer=").append(releaseVer);
		sb.append(", releaseDate=").append(releaseDate);
		sb.append(", stuff=").append(stuff);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Releases other = (Releases) that;
		return (this.getReleaseId() == null ? other.getReleaseId() == null
				: this.getReleaseId().equals(other.getReleaseId()))
				&& (this.getRevId() == null ? other.getRevId() == null : this.getRevId().equals(other.getRevId()))
				&& (this.getReleaseVer() == null ? other.getReleaseVer() == null
						: this.getReleaseVer().equals(other.getReleaseVer()))
				&& (this.getReleaseDate() == null ? other.getReleaseDate() == null
						: this.getReleaseDate().equals(other.getReleaseDate()))
				&& (this.getStuff() == null ? other.getStuff() == null : this.getStuff().equals(other.getStuff()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getReleaseId() == null) ? 0 : getReleaseId().hashCode());
		result = prime * result + ((getRevId() == null) ? 0 : getRevId().hashCode());
		result = prime * result + ((getReleaseVer() == null) ? 0 : getReleaseVer().hashCode());
		result = prime * result + ((getReleaseDate() == null) ? 0 : getReleaseDate().hashCode());
		result = prime * result + ((getStuff() == null) ? 0 : getStuff().hashCode());
		return result;
	}
}