package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import q4s.tutorials.mybatis.BaseEntity;

public class Revisions extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISIONS.REV_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long revId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISIONS.PROJECT_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long projectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISIONS.MINOR_VER
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Integer minorVer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISIONS.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISIONS.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String stuff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Revisions(Long revId, Long projectId, Integer minorVer, String code) {
		this.revId = revId;
		this.projectId = projectId;
		this.minorVer = minorVer;
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Revisions(Long revId, Long projectId, Integer minorVer, String code, String stuff) {
		this.revId = revId;
		this.projectId = projectId;
		this.minorVer = minorVer;
		this.code = code;
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Revisions() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISIONS.REV_ID
	 * @return  the value of REVISIONS.REV_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getRevId() {
		return revId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISIONS.REV_ID
	 * @param revId  the value for REVISIONS.REV_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setRevId(Long revId) {
		this.revId = revId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISIONS.PROJECT_ID
	 * @return  the value of REVISIONS.PROJECT_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISIONS.PROJECT_ID
	 * @param projectId  the value for REVISIONS.PROJECT_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISIONS.MINOR_VER
	 * @return  the value of REVISIONS.MINOR_VER
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Integer getMinorVer() {
		return minorVer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISIONS.MINOR_VER
	 * @param minorVer  the value for REVISIONS.MINOR_VER
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setMinorVer(Integer minorVer) {
		this.minorVer = minorVer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISIONS.CODE
	 * @return  the value of REVISIONS.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISIONS.CODE
	 * @param code  the value for REVISIONS.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISIONS.STUFF
	 * @return  the value of REVISIONS.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getStuff() {
		return stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISIONS.STUFF
	 * @param stuff  the value for REVISIONS.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setStuff(String stuff) {
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", revId=").append(revId);
		sb.append(", projectId=").append(projectId);
		sb.append(", minorVer=").append(minorVer);
		sb.append(", code=").append(code);
		sb.append(", stuff=").append(stuff);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Revisions other = (Revisions) that;
		return (this.getRevId() == null ? other.getRevId() == null : this.getRevId().equals(other.getRevId()))
				&& (this.getProjectId() == null ? other.getProjectId() == null
						: this.getProjectId().equals(other.getProjectId()))
				&& (this.getMinorVer() == null ? other.getMinorVer() == null
						: this.getMinorVer().equals(other.getMinorVer()))
				&& (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
				&& (this.getStuff() == null ? other.getStuff() == null : this.getStuff().equals(other.getStuff()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getRevId() == null) ? 0 : getRevId().hashCode());
		result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
		result = prime * result + ((getMinorVer() == null) ? 0 : getMinorVer().hashCode());
		result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
		result = prime * result + ((getStuff() == null) ? 0 : getStuff().hashCode());
		return result;
	}
}