package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import java.util.Date;

public class RevisionHist extends RevisionHistKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISION_HIST.STATE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long stateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISION_HIST.MANAGER_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISION_HIST.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String stuff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public RevisionHist(Long revId, Date dat, Date datto, Long stateId, Long managerId) {
		super(revId, dat, datto);
		this.stateId = stateId;
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public RevisionHist(Long revId, Date dat, Date datto, Long stateId, Long managerId, String stuff) {
		super(revId, dat, datto);
		this.stateId = stateId;
		this.managerId = managerId;
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public RevisionHist() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISION_HIST.STATE_ID
	 * @return  the value of REVISION_HIST.STATE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISION_HIST.STATE_ID
	 * @param stateId  the value for REVISION_HIST.STATE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setStateId(Long stateId) {
		this.stateId = stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISION_HIST.MANAGER_ID
	 * @return  the value of REVISION_HIST.MANAGER_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISION_HIST.MANAGER_ID
	 * @param managerId  the value for REVISION_HIST.MANAGER_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setManagerId(Long managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISION_HIST.STUFF
	 * @return  the value of REVISION_HIST.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getStuff() {
		return stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISION_HIST.STUFF
	 * @param stuff  the value for REVISION_HIST.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setStuff(String stuff) {
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", stateId=").append(stateId);
		sb.append(", managerId=").append(managerId);
		sb.append(", stuff=").append(stuff);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		RevisionHist other = (RevisionHist) that;
		return (this.getRevId() == null ? other.getRevId() == null : this.getRevId().equals(other.getRevId()))
				&& (this.getDat() == null ? other.getDat() == null : this.getDat().equals(other.getDat()))
				&& (this.getDatto() == null ? other.getDatto() == null : this.getDatto().equals(other.getDatto()))
				&& (this.getStateId() == null ? other.getStateId() == null
						: this.getStateId().equals(other.getStateId()))
				&& (this.getManagerId() == null ? other.getManagerId() == null
						: this.getManagerId().equals(other.getManagerId()))
				&& (this.getStuff() == null ? other.getStuff() == null : this.getStuff().equals(other.getStuff()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getRevId() == null) ? 0 : getRevId().hashCode());
		result = prime * result + ((getDat() == null) ? 0 : getDat().hashCode());
		result = prime * result + ((getDatto() == null) ? 0 : getDatto().hashCode());
		result = prime * result + ((getStateId() == null) ? 0 : getStateId().hashCode());
		result = prime * result + ((getManagerId() == null) ? 0 : getManagerId().hashCode());
		result = prime * result + ((getStuff() == null) ? 0 : getStuff().hashCode());
		return result;
	}
}