package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import q4s.tutorials.mybatis.BaseEntity;

public class RevisionStates extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISION_STATES.STATE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long stateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISION_STATES.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISION_STATES.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column REVISION_STATES.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public RevisionStates(Long stateId, String code, String title, String description) {
		this.stateId = stateId;
		this.code = code;
		this.title = title;
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public RevisionStates() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISION_STATES.STATE_ID
	 * @return  the value of REVISION_STATES.STATE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISION_STATES.STATE_ID
	 * @param stateId  the value for REVISION_STATES.STATE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setStateId(Long stateId) {
		this.stateId = stateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISION_STATES.CODE
	 * @return  the value of REVISION_STATES.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISION_STATES.CODE
	 * @param code  the value for REVISION_STATES.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISION_STATES.TITLE
	 * @return  the value of REVISION_STATES.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISION_STATES.TITLE
	 * @param title  the value for REVISION_STATES.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column REVISION_STATES.DESCRIPTION
	 * @return  the value of REVISION_STATES.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column REVISION_STATES.DESCRIPTION
	 * @param description  the value for REVISION_STATES.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", stateId=").append(stateId);
		sb.append(", code=").append(code);
		sb.append(", title=").append(title);
		sb.append(", description=").append(description);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		RevisionStates other = (RevisionStates) that;
		return (this.getStateId() == null ? other.getStateId() == null : this.getStateId().equals(other.getStateId()))
				&& (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getStateId() == null) ? 0 : getStateId().hashCode());
		result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		return result;
	}
}