package q4s.tutorials.mybatis.annot.entity;

import java.util.ArrayList;
import java.util.List;

public class RevisionsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public RevisionsExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRevIdIsNull() {
			addCriterion("REV_ID is null");
			return (Criteria) this;
		}

		public Criteria andRevIdIsNotNull() {
			addCriterion("REV_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRevIdEqualTo(Long value) {
			addCriterion("REV_ID =", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdNotEqualTo(Long value) {
			addCriterion("REV_ID <>", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdGreaterThan(Long value) {
			addCriterion("REV_ID >", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdGreaterThanOrEqualTo(Long value) {
			addCriterion("REV_ID >=", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdLessThan(Long value) {
			addCriterion("REV_ID <", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdLessThanOrEqualTo(Long value) {
			addCriterion("REV_ID <=", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdIn(List<Long> values) {
			addCriterion("REV_ID in", values, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdNotIn(List<Long> values) {
			addCriterion("REV_ID not in", values, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdBetween(Long value1, Long value2) {
			addCriterion("REV_ID between", value1, value2, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdNotBetween(Long value1, Long value2) {
			addCriterion("REV_ID not between", value1, value2, "revId");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNull() {
			addCriterion("PROJECT_ID is null");
			return (Criteria) this;
		}

		public Criteria andProjectIdIsNotNull() {
			addCriterion("PROJECT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andProjectIdEqualTo(Long value) {
			addCriterion("PROJECT_ID =", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotEqualTo(Long value) {
			addCriterion("PROJECT_ID <>", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThan(Long value) {
			addCriterion("PROJECT_ID >", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
			addCriterion("PROJECT_ID >=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThan(Long value) {
			addCriterion("PROJECT_ID <", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdLessThanOrEqualTo(Long value) {
			addCriterion("PROJECT_ID <=", value, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdIn(List<Long> values) {
			addCriterion("PROJECT_ID in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotIn(List<Long> values) {
			addCriterion("PROJECT_ID not in", values, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdBetween(Long value1, Long value2) {
			addCriterion("PROJECT_ID between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andProjectIdNotBetween(Long value1, Long value2) {
			addCriterion("PROJECT_ID not between", value1, value2, "projectId");
			return (Criteria) this;
		}

		public Criteria andMinorVerIsNull() {
			addCriterion("MINOR_VER is null");
			return (Criteria) this;
		}

		public Criteria andMinorVerIsNotNull() {
			addCriterion("MINOR_VER is not null");
			return (Criteria) this;
		}

		public Criteria andMinorVerEqualTo(Integer value) {
			addCriterion("MINOR_VER =", value, "minorVer");
			return (Criteria) this;
		}

		public Criteria andMinorVerNotEqualTo(Integer value) {
			addCriterion("MINOR_VER <>", value, "minorVer");
			return (Criteria) this;
		}

		public Criteria andMinorVerGreaterThan(Integer value) {
			addCriterion("MINOR_VER >", value, "minorVer");
			return (Criteria) this;
		}

		public Criteria andMinorVerGreaterThanOrEqualTo(Integer value) {
			addCriterion("MINOR_VER >=", value, "minorVer");
			return (Criteria) this;
		}

		public Criteria andMinorVerLessThan(Integer value) {
			addCriterion("MINOR_VER <", value, "minorVer");
			return (Criteria) this;
		}

		public Criteria andMinorVerLessThanOrEqualTo(Integer value) {
			addCriterion("MINOR_VER <=", value, "minorVer");
			return (Criteria) this;
		}

		public Criteria andMinorVerIn(List<Integer> values) {
			addCriterion("MINOR_VER in", values, "minorVer");
			return (Criteria) this;
		}

		public Criteria andMinorVerNotIn(List<Integer> values) {
			addCriterion("MINOR_VER not in", values, "minorVer");
			return (Criteria) this;
		}

		public Criteria andMinorVerBetween(Integer value1, Integer value2) {
			addCriterion("MINOR_VER between", value1, value2, "minorVer");
			return (Criteria) this;
		}

		public Criteria andMinorVerNotBetween(Integer value1, Integer value2) {
			addCriterion("MINOR_VER not between", value1, value2, "minorVer");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("CODE is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("CODE is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("CODE =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("CODE <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("CODE >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("CODE >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("CODE <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("CODE <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("CODE like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("CODE not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("CODE in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("CODE not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("CODE between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("CODE not between", value1, value2, "code");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REVISIONS
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 19 17:36:56 MSK 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}