package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import q4s.tutorials.mybatis.BaseEntity;

public class Skills extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKILLS.SKILL_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long skillId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKILLS.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKILLS.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKILLS.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Skills(Long skillId, String code, String title, String description) {
		this.skillId = skillId;
		this.code = code;
		this.title = title;
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Skills() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKILLS.SKILL_ID
	 * @return  the value of SKILLS.SKILL_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getSkillId() {
		return skillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKILLS.SKILL_ID
	 * @param skillId  the value for SKILLS.SKILL_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setSkillId(Long skillId) {
		this.skillId = skillId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKILLS.CODE
	 * @return  the value of SKILLS.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKILLS.CODE
	 * @param code  the value for SKILLS.CODE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKILLS.TITLE
	 * @return  the value of SKILLS.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKILLS.TITLE
	 * @param title  the value for SKILLS.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKILLS.DESCRIPTION
	 * @return  the value of SKILLS.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKILLS.DESCRIPTION
	 * @param description  the value for SKILLS.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", skillId=").append(skillId);
		sb.append(", code=").append(code);
		sb.append(", title=").append(title);
		sb.append(", description=").append(description);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Skills other = (Skills) that;
		return (this.getSkillId() == null ? other.getSkillId() == null : this.getSkillId().equals(other.getSkillId()))
				&& (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getSkillId() == null) ? 0 : getSkillId().hashCode());
		result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		return result;
	}
}