package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import q4s.tutorials.mybatis.BaseEntity;

public class Tags extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TAGS.TAG_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String tagId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Tags(String tagId) {
		this.tagId = tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Tags() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TAGS.TAG_ID
	 * @return  the value of TAGS.TAG_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getTagId() {
		return tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TAGS.TAG_ID
	 * @param tagId  the value for TAGS.TAG_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setTagId(String tagId) {
		this.tagId = tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", tagId=").append(tagId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Tags other = (Tags) that;
		return (this.getTagId() == null ? other.getTagId() == null : this.getTagId().equals(other.getTagId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getTagId() == null) ? 0 : getTagId().hashCode());
		return result;
	}
}