package q4s.tutorials.mybatis.annot.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TasksExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public TasksExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andTaskIdIsNull() {
			addCriterion("TASK_ID is null");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNotNull() {
			addCriterion("TASK_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTaskIdEqualTo(Long value) {
			addCriterion("TASK_ID =", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotEqualTo(Long value) {
			addCriterion("TASK_ID <>", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThan(Long value) {
			addCriterion("TASK_ID >", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThanOrEqualTo(Long value) {
			addCriterion("TASK_ID >=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThan(Long value) {
			addCriterion("TASK_ID <", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThanOrEqualTo(Long value) {
			addCriterion("TASK_ID <=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdIn(List<Long> values) {
			addCriterion("TASK_ID in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotIn(List<Long> values) {
			addCriterion("TASK_ID not in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdBetween(Long value1, Long value2) {
			addCriterion("TASK_ID between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotBetween(Long value1, Long value2) {
			addCriterion("TASK_ID not between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andRevIdIsNull() {
			addCriterion("REV_ID is null");
			return (Criteria) this;
		}

		public Criteria andRevIdIsNotNull() {
			addCriterion("REV_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRevIdEqualTo(Long value) {
			addCriterion("REV_ID =", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdNotEqualTo(Long value) {
			addCriterion("REV_ID <>", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdGreaterThan(Long value) {
			addCriterion("REV_ID >", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdGreaterThanOrEqualTo(Long value) {
			addCriterion("REV_ID >=", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdLessThan(Long value) {
			addCriterion("REV_ID <", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdLessThanOrEqualTo(Long value) {
			addCriterion("REV_ID <=", value, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdIn(List<Long> values) {
			addCriterion("REV_ID in", values, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdNotIn(List<Long> values) {
			addCriterion("REV_ID not in", values, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdBetween(Long value1, Long value2) {
			addCriterion("REV_ID between", value1, value2, "revId");
			return (Criteria) this;
		}

		public Criteria andRevIdNotBetween(Long value1, Long value2) {
			addCriterion("REV_ID not between", value1, value2, "revId");
			return (Criteria) this;
		}

		public Criteria andModuleIdIsNull() {
			addCriterion("MODULE_ID is null");
			return (Criteria) this;
		}

		public Criteria andModuleIdIsNotNull() {
			addCriterion("MODULE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andModuleIdEqualTo(Long value) {
			addCriterion("MODULE_ID =", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotEqualTo(Long value) {
			addCriterion("MODULE_ID <>", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdGreaterThan(Long value) {
			addCriterion("MODULE_ID >", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdGreaterThanOrEqualTo(Long value) {
			addCriterion("MODULE_ID >=", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdLessThan(Long value) {
			addCriterion("MODULE_ID <", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdLessThanOrEqualTo(Long value) {
			addCriterion("MODULE_ID <=", value, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdIn(List<Long> values) {
			addCriterion("MODULE_ID in", values, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotIn(List<Long> values) {
			addCriterion("MODULE_ID not in", values, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdBetween(Long value1, Long value2) {
			addCriterion("MODULE_ID between", value1, value2, "moduleId");
			return (Criteria) this;
		}

		public Criteria andModuleIdNotBetween(Long value1, Long value2) {
			addCriterion("MODULE_ID not between", value1, value2, "moduleId");
			return (Criteria) this;
		}

		public Criteria andDatIsNull() {
			addCriterion("DAT is null");
			return (Criteria) this;
		}

		public Criteria andDatIsNotNull() {
			addCriterion("DAT is not null");
			return (Criteria) this;
		}

		public Criteria andDatEqualTo(Date value) {
			addCriterionForJDBCDate("DAT =", value, "dat");
			return (Criteria) this;
		}

		public Criteria andDatNotEqualTo(Date value) {
			addCriterionForJDBCDate("DAT <>", value, "dat");
			return (Criteria) this;
		}

		public Criteria andDatGreaterThan(Date value) {
			addCriterionForJDBCDate("DAT >", value, "dat");
			return (Criteria) this;
		}

		public Criteria andDatGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DAT >=", value, "dat");
			return (Criteria) this;
		}

		public Criteria andDatLessThan(Date value) {
			addCriterionForJDBCDate("DAT <", value, "dat");
			return (Criteria) this;
		}

		public Criteria andDatLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DAT <=", value, "dat");
			return (Criteria) this;
		}

		public Criteria andDatIn(List<Date> values) {
			addCriterionForJDBCDate("DAT in", values, "dat");
			return (Criteria) this;
		}

		public Criteria andDatNotIn(List<Date> values) {
			addCriterionForJDBCDate("DAT not in", values, "dat");
			return (Criteria) this;
		}

		public Criteria andDatBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DAT between", value1, value2, "dat");
			return (Criteria) this;
		}

		public Criteria andDatNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DAT not between", value1, value2, "dat");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("TITLE is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("TITLE =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("TITLE <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("TITLE >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("TITLE >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("TITLE <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("TITLE <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("TITLE like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("TITLE not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("TITLE in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("TITLE not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("TITLE between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("TITLE not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("DESCRIPTION is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("DESCRIPTION like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("DESCRIPTION in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("DESCRIPTION not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andAuthorIdIsNull() {
			addCriterion("AUTHOR_ID is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIdIsNotNull() {
			addCriterion("AUTHOR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorIdEqualTo(Long value) {
			addCriterion("AUTHOR_ID =", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdNotEqualTo(Long value) {
			addCriterion("AUTHOR_ID <>", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdGreaterThan(Long value) {
			addCriterion("AUTHOR_ID >", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdGreaterThanOrEqualTo(Long value) {
			addCriterion("AUTHOR_ID >=", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdLessThan(Long value) {
			addCriterion("AUTHOR_ID <", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdLessThanOrEqualTo(Long value) {
			addCriterion("AUTHOR_ID <=", value, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdIn(List<Long> values) {
			addCriterion("AUTHOR_ID in", values, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdNotIn(List<Long> values) {
			addCriterion("AUTHOR_ID not in", values, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdBetween(Long value1, Long value2) {
			addCriterion("AUTHOR_ID between", value1, value2, "authorId");
			return (Criteria) this;
		}

		public Criteria andAuthorIdNotBetween(Long value1, Long value2) {
			addCriterion("AUTHOR_ID not between", value1, value2, "authorId");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNull() {
			addCriterion("PARENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNotNull() {
			addCriterion("PARENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andParentIdEqualTo(Long value) {
			addCriterion("PARENT_ID =", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotEqualTo(Long value) {
			addCriterion("PARENT_ID <>", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThan(Long value) {
			addCriterion("PARENT_ID >", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
			addCriterion("PARENT_ID >=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThan(Long value) {
			addCriterion("PARENT_ID <", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThanOrEqualTo(Long value) {
			addCriterion("PARENT_ID <=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdIn(List<Long> values) {
			addCriterion("PARENT_ID in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotIn(List<Long> values) {
			addCriterion("PARENT_ID not in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdBetween(Long value1, Long value2) {
			addCriterion("PARENT_ID between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotBetween(Long value1, Long value2) {
			addCriterion("PARENT_ID not between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNull() {
			addCriterion("TYPE_ID is null");
			return (Criteria) this;
		}

		public Criteria andTypeIdIsNotNull() {
			addCriterion("TYPE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTypeIdEqualTo(Long value) {
			addCriterion("TYPE_ID =", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotEqualTo(Long value) {
			addCriterion("TYPE_ID <>", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThan(Long value) {
			addCriterion("TYPE_ID >", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdGreaterThanOrEqualTo(Long value) {
			addCriterion("TYPE_ID >=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThan(Long value) {
			addCriterion("TYPE_ID <", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdLessThanOrEqualTo(Long value) {
			addCriterion("TYPE_ID <=", value, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdIn(List<Long> values) {
			addCriterion("TYPE_ID in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotIn(List<Long> values) {
			addCriterion("TYPE_ID not in", values, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdBetween(Long value1, Long value2) {
			addCriterion("TYPE_ID between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andTypeIdNotBetween(Long value1, Long value2) {
			addCriterion("TYPE_ID not between", value1, value2, "typeId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdIsNull() {
			addCriterion("PRIORITY_ID is null");
			return (Criteria) this;
		}

		public Criteria andPriorityIdIsNotNull() {
			addCriterion("PRIORITY_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPriorityIdEqualTo(Long value) {
			addCriterion("PRIORITY_ID =", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdNotEqualTo(Long value) {
			addCriterion("PRIORITY_ID <>", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdGreaterThan(Long value) {
			addCriterion("PRIORITY_ID >", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdGreaterThanOrEqualTo(Long value) {
			addCriterion("PRIORITY_ID >=", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdLessThan(Long value) {
			addCriterion("PRIORITY_ID <", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdLessThanOrEqualTo(Long value) {
			addCriterion("PRIORITY_ID <=", value, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdIn(List<Long> values) {
			addCriterion("PRIORITY_ID in", values, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdNotIn(List<Long> values) {
			addCriterion("PRIORITY_ID not in", values, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdBetween(Long value1, Long value2) {
			addCriterion("PRIORITY_ID between", value1, value2, "priorityId");
			return (Criteria) this;
		}

		public Criteria andPriorityIdNotBetween(Long value1, Long value2) {
			addCriterion("PRIORITY_ID not between", value1, value2, "priorityId");
			return (Criteria) this;
		}

		public Criteria andDatPlanIsNull() {
			addCriterion("DAT_PLAN is null");
			return (Criteria) this;
		}

		public Criteria andDatPlanIsNotNull() {
			addCriterion("DAT_PLAN is not null");
			return (Criteria) this;
		}

		public Criteria andDatPlanEqualTo(Date value) {
			addCriterionForJDBCDate("DAT_PLAN =", value, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatPlanNotEqualTo(Date value) {
			addCriterionForJDBCDate("DAT_PLAN <>", value, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatPlanGreaterThan(Date value) {
			addCriterionForJDBCDate("DAT_PLAN >", value, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatPlanGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DAT_PLAN >=", value, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatPlanLessThan(Date value) {
			addCriterionForJDBCDate("DAT_PLAN <", value, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatPlanLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DAT_PLAN <=", value, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatPlanIn(List<Date> values) {
			addCriterionForJDBCDate("DAT_PLAN in", values, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatPlanNotIn(List<Date> values) {
			addCriterionForJDBCDate("DAT_PLAN not in", values, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatPlanBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DAT_PLAN between", value1, value2, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatPlanNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DAT_PLAN not between", value1, value2, "datPlan");
			return (Criteria) this;
		}

		public Criteria andDatFactIsNull() {
			addCriterion("DAT_FACT is null");
			return (Criteria) this;
		}

		public Criteria andDatFactIsNotNull() {
			addCriterion("DAT_FACT is not null");
			return (Criteria) this;
		}

		public Criteria andDatFactEqualTo(Date value) {
			addCriterionForJDBCDate("DAT_FACT =", value, "datFact");
			return (Criteria) this;
		}

		public Criteria andDatFactNotEqualTo(Date value) {
			addCriterionForJDBCDate("DAT_FACT <>", value, "datFact");
			return (Criteria) this;
		}

		public Criteria andDatFactGreaterThan(Date value) {
			addCriterionForJDBCDate("DAT_FACT >", value, "datFact");
			return (Criteria) this;
		}

		public Criteria andDatFactGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DAT_FACT >=", value, "datFact");
			return (Criteria) this;
		}

		public Criteria andDatFactLessThan(Date value) {
			addCriterionForJDBCDate("DAT_FACT <", value, "datFact");
			return (Criteria) this;
		}

		public Criteria andDatFactLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("DAT_FACT <=", value, "datFact");
			return (Criteria) this;
		}

		public Criteria andDatFactIn(List<Date> values) {
			addCriterionForJDBCDate("DAT_FACT in", values, "datFact");
			return (Criteria) this;
		}

		public Criteria andDatFactNotIn(List<Date> values) {
			addCriterionForJDBCDate("DAT_FACT not in", values, "datFact");
			return (Criteria) this;
		}

		public Criteria andDatFactBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DAT_FACT between", value1, value2, "datFact");
			return (Criteria) this;
		}

		public Criteria andDatFactNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("DAT_FACT not between", value1, value2, "datFact");
			return (Criteria) this;
		}

		public Criteria andReleaseIdIsNull() {
			addCriterion("RELEASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andReleaseIdIsNotNull() {
			addCriterion("RELEASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andReleaseIdEqualTo(Long value) {
			addCriterion("RELEASE_ID =", value, "releaseId");
			return (Criteria) this;
		}

		public Criteria andReleaseIdNotEqualTo(Long value) {
			addCriterion("RELEASE_ID <>", value, "releaseId");
			return (Criteria) this;
		}

		public Criteria andReleaseIdGreaterThan(Long value) {
			addCriterion("RELEASE_ID >", value, "releaseId");
			return (Criteria) this;
		}

		public Criteria andReleaseIdGreaterThanOrEqualTo(Long value) {
			addCriterion("RELEASE_ID >=", value, "releaseId");
			return (Criteria) this;
		}

		public Criteria andReleaseIdLessThan(Long value) {
			addCriterion("RELEASE_ID <", value, "releaseId");
			return (Criteria) this;
		}

		public Criteria andReleaseIdLessThanOrEqualTo(Long value) {
			addCriterion("RELEASE_ID <=", value, "releaseId");
			return (Criteria) this;
		}

		public Criteria andReleaseIdIn(List<Long> values) {
			addCriterion("RELEASE_ID in", values, "releaseId");
			return (Criteria) this;
		}

		public Criteria andReleaseIdNotIn(List<Long> values) {
			addCriterion("RELEASE_ID not in", values, "releaseId");
			return (Criteria) this;
		}

		public Criteria andReleaseIdBetween(Long value1, Long value2) {
			addCriterion("RELEASE_ID between", value1, value2, "releaseId");
			return (Criteria) this;
		}

		public Criteria andReleaseIdNotBetween(Long value1, Long value2) {
			addCriterion("RELEASE_ID not between", value1, value2, "releaseId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TASKS
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 19 17:36:56 MSK 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}