package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import java.util.Date;
import q4s.tutorials.mybatis.BaseEntity;

public class Tasks extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.TASK_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.REV_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long revId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.MODULE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.DAT
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Date dat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.AUTHOR_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.PARENT_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.TYPE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.PRIORITY_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long priorityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.DAT_PLAN
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Date datPlan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.DAT_FACT
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Date datFact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.RELEASE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long releaseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private String stuff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Tasks(Long taskId, Long revId, Long moduleId, Date dat, String title, String description, Long authorId,
			Long parentId, Long typeId, Long priorityId, Date datPlan, Date datFact, Long releaseId) {
		this.taskId = taskId;
		this.revId = revId;
		this.moduleId = moduleId;
		this.dat = dat;
		this.title = title;
		this.description = description;
		this.authorId = authorId;
		this.parentId = parentId;
		this.typeId = typeId;
		this.priorityId = priorityId;
		this.datPlan = datPlan;
		this.datFact = datFact;
		this.releaseId = releaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Tasks(Long taskId, Long revId, Long moduleId, Date dat, String title, String description, Long authorId,
			Long parentId, Long typeId, Long priorityId, Date datPlan, Date datFact, Long releaseId, String stuff) {
		this.taskId = taskId;
		this.revId = revId;
		this.moduleId = moduleId;
		this.dat = dat;
		this.title = title;
		this.description = description;
		this.authorId = authorId;
		this.parentId = parentId;
		this.typeId = typeId;
		this.priorityId = priorityId;
		this.datPlan = datPlan;
		this.datFact = datFact;
		this.releaseId = releaseId;
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Tasks() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.TASK_ID
	 * @return  the value of TASKS.TASK_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.TASK_ID
	 * @param taskId  the value for TASKS.TASK_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.REV_ID
	 * @return  the value of TASKS.REV_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getRevId() {
		return revId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.REV_ID
	 * @param revId  the value for TASKS.REV_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setRevId(Long revId) {
		this.revId = revId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.MODULE_ID
	 * @return  the value of TASKS.MODULE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getModuleId() {
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.MODULE_ID
	 * @param moduleId  the value for TASKS.MODULE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setModuleId(Long moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.DAT
	 * @return  the value of TASKS.DAT
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Date getDat() {
		return dat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.DAT
	 * @param dat  the value for TASKS.DAT
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDat(Date dat) {
		this.dat = dat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.TITLE
	 * @return  the value of TASKS.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.TITLE
	 * @param title  the value for TASKS.TITLE
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.DESCRIPTION
	 * @return  the value of TASKS.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.DESCRIPTION
	 * @param description  the value for TASKS.DESCRIPTION
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.AUTHOR_ID
	 * @return  the value of TASKS.AUTHOR_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.AUTHOR_ID
	 * @param authorId  the value for TASKS.AUTHOR_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setAuthorId(Long authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.PARENT_ID
	 * @return  the value of TASKS.PARENT_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.PARENT_ID
	 * @param parentId  the value for TASKS.PARENT_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.TYPE_ID
	 * @return  the value of TASKS.TYPE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.TYPE_ID
	 * @param typeId  the value for TASKS.TYPE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.PRIORITY_ID
	 * @return  the value of TASKS.PRIORITY_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getPriorityId() {
		return priorityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.PRIORITY_ID
	 * @param priorityId  the value for TASKS.PRIORITY_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setPriorityId(Long priorityId) {
		this.priorityId = priorityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.DAT_PLAN
	 * @return  the value of TASKS.DAT_PLAN
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Date getDatPlan() {
		return datPlan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.DAT_PLAN
	 * @param datPlan  the value for TASKS.DAT_PLAN
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDatPlan(Date datPlan) {
		this.datPlan = datPlan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.DAT_FACT
	 * @return  the value of TASKS.DAT_FACT
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Date getDatFact() {
		return datFact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.DAT_FACT
	 * @param datFact  the value for TASKS.DAT_FACT
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDatFact(Date datFact) {
		this.datFact = datFact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.RELEASE_ID
	 * @return  the value of TASKS.RELEASE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getReleaseId() {
		return releaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.RELEASE_ID
	 * @param releaseId  the value for TASKS.RELEASE_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setReleaseId(Long releaseId) {
		this.releaseId = releaseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS.STUFF
	 * @return  the value of TASKS.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public String getStuff() {
		return stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS.STUFF
	 * @param stuff  the value for TASKS.STUFF
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setStuff(String stuff) {
		this.stuff = stuff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", taskId=").append(taskId);
		sb.append(", revId=").append(revId);
		sb.append(", moduleId=").append(moduleId);
		sb.append(", dat=").append(dat);
		sb.append(", title=").append(title);
		sb.append(", description=").append(description);
		sb.append(", authorId=").append(authorId);
		sb.append(", parentId=").append(parentId);
		sb.append(", typeId=").append(typeId);
		sb.append(", priorityId=").append(priorityId);
		sb.append(", datPlan=").append(datPlan);
		sb.append(", datFact=").append(datFact);
		sb.append(", releaseId=").append(releaseId);
		sb.append(", stuff=").append(stuff);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Tasks other = (Tasks) that;
		return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
				&& (this.getRevId() == null ? other.getRevId() == null : this.getRevId().equals(other.getRevId()))
				&& (this.getModuleId() == null ? other.getModuleId() == null
						: this.getModuleId().equals(other.getModuleId()))
				&& (this.getDat() == null ? other.getDat() == null : this.getDat().equals(other.getDat()))
				&& (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
				&& (this.getDescription() == null ? other.getDescription() == null
						: this.getDescription().equals(other.getDescription()))
				&& (this.getAuthorId() == null ? other.getAuthorId() == null
						: this.getAuthorId().equals(other.getAuthorId()))
				&& (this.getParentId() == null ? other.getParentId() == null
						: this.getParentId().equals(other.getParentId()))
				&& (this.getTypeId() == null ? other.getTypeId() == null : this.getTypeId().equals(other.getTypeId()))
				&& (this.getPriorityId() == null ? other.getPriorityId() == null
						: this.getPriorityId().equals(other.getPriorityId()))
				&& (this.getDatPlan() == null ? other.getDatPlan() == null
						: this.getDatPlan().equals(other.getDatPlan()))
				&& (this.getDatFact() == null ? other.getDatFact() == null
						: this.getDatFact().equals(other.getDatFact()))
				&& (this.getReleaseId() == null ? other.getReleaseId() == null
						: this.getReleaseId().equals(other.getReleaseId()))
				&& (this.getStuff() == null ? other.getStuff() == null : this.getStuff().equals(other.getStuff()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
		result = prime * result + ((getRevId() == null) ? 0 : getRevId().hashCode());
		result = prime * result + ((getModuleId() == null) ? 0 : getModuleId().hashCode());
		result = prime * result + ((getDat() == null) ? 0 : getDat().hashCode());
		result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
		result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
		result = prime * result + ((getAuthorId() == null) ? 0 : getAuthorId().hashCode());
		result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
		result = prime * result + ((getTypeId() == null) ? 0 : getTypeId().hashCode());
		result = prime * result + ((getPriorityId() == null) ? 0 : getPriorityId().hashCode());
		result = prime * result + ((getDatPlan() == null) ? 0 : getDatPlan().hashCode());
		result = prime * result + ((getDatFact() == null) ? 0 : getDatFact().hashCode());
		result = prime * result + ((getReleaseId() == null) ? 0 : getReleaseId().hashCode());
		result = prime * result + ((getStuff() == null) ? 0 : getStuff().hashCode());
		return result;
	}
}