package q4s.tutorials.mybatis.annot.entity;

import java.io.Serializable;
import java.util.Date;
import q4s.tutorials.mybatis.BaseEntity;

public class TasksHistKey extends BaseEntity implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS_HIST.TASK_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Long taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS_HIST.DAT
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Date dat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TASKS_HIST.DATTO
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private Date datto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TASKS_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public TasksHistKey(Long taskId, Date dat, Date datto) {
		this.taskId = taskId;
		this.dat = dat;
		this.datto = datto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public TasksHistKey() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS_HIST.TASK_ID
	 * @return  the value of TASKS_HIST.TASK_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Long getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS_HIST.TASK_ID
	 * @param taskId  the value for TASKS_HIST.TASK_ID
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS_HIST.DAT
	 * @return  the value of TASKS_HIST.DAT
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Date getDat() {
		return dat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS_HIST.DAT
	 * @param dat  the value for TASKS_HIST.DAT
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDat(Date dat) {
		this.dat = dat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TASKS_HIST.DATTO
	 * @return  the value of TASKS_HIST.DATTO
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public Date getDatto() {
		return datto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TASKS_HIST.DATTO
	 * @param datto  the value for TASKS_HIST.DATTO
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	public void setDatto(Date datto) {
		this.datto = datto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", taskId=").append(taskId);
		sb.append(", dat=").append(dat);
		sb.append(", datto=").append(datto);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TasksHistKey other = (TasksHistKey) that;
		return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
				&& (this.getDat() == null ? other.getDat() == null : this.getDat().equals(other.getDat()))
				&& (this.getDatto() == null ? other.getDatto() == null : this.getDatto().equals(other.getDatto()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASKS_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
		result = prime * result + ((getDat() == null) ? 0 : getDat().hashCode());
		result = prime * result + ((getDatto() == null) ? 0 : getDatto().hashCode());
		return result;
	}
}