package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.Modules;
import q4s.tutorials.mybatis.annot.entity.ModulesExample;

public interface ModulesMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(ModulesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(ModulesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(Long moduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(Modules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(Modules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<Modules> selectByExampleWithBLOBs(ModulesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<Modules> selectByExample(ModulesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	Modules selectByPrimaryKey(Long moduleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") Modules record, @Param("example") ModulesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") Modules record, @Param("example") ModulesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") Modules record, @Param("example") ModulesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeySelective(Modules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeyWithBLOBs(Modules record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODULES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKey(Modules record);
}