package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.Priorities;
import q4s.tutorials.mybatis.annot.entity.PrioritiesExample;

public interface PrioritiesMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(PrioritiesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(PrioritiesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(Long priorityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(Priorities record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(Priorities record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<Priorities> selectByExample(PrioritiesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	Priorities selectByPrimaryKey(Long priorityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") Priorities record, @Param("example") PrioritiesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") Priorities record, @Param("example") PrioritiesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeySelective(Priorities record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PRIORITIES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKey(Priorities record);
}