package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.ProjectStates;
import q4s.tutorials.mybatis.annot.entity.ProjectStatesExample;

public interface ProjectStatesMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(ProjectStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(ProjectStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(Long stateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(ProjectStates record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(ProjectStates record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<ProjectStates> selectByExample(ProjectStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	ProjectStates selectByPrimaryKey(Long stateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") ProjectStates record, @Param("example") ProjectStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") ProjectStates record, @Param("example") ProjectStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeySelective(ProjectStates record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROJECT_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKey(ProjectStates record);
}