package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.Releases;
import q4s.tutorials.mybatis.annot.entity.ReleasesExample;

public interface ReleasesMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(ReleasesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(ReleasesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(Long releaseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(Releases record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(Releases record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<Releases> selectByExampleWithBLOBs(ReleasesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<Releases> selectByExample(ReleasesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	Releases selectByPrimaryKey(Long releaseId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") Releases record, @Param("example") ReleasesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") Releases record, @Param("example") ReleasesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") Releases record, @Param("example") ReleasesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeySelective(Releases record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeyWithBLOBs(Releases record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RELEASES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKey(Releases record);
}