package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.RevisionStates;
import q4s.tutorials.mybatis.annot.entity.RevisionStatesExample;

public interface RevisionStatesMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(RevisionStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(RevisionStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(Long stateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(RevisionStates record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(RevisionStates record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<RevisionStates> selectByExample(RevisionStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	RevisionStates selectByPrimaryKey(Long stateId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") RevisionStates record,
			@Param("example") RevisionStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") RevisionStates record, @Param("example") RevisionStatesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeySelective(RevisionStates record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_STATES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKey(RevisionStates record);
}