package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.Revisions;
import q4s.tutorials.mybatis.annot.entity.RevisionsExample;

public interface RevisionsMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(RevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(RevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(Long revId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(Revisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(Revisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<Revisions> selectByExampleWithBLOBs(RevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<Revisions> selectByExample(RevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	Revisions selectByPrimaryKey(Long revId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") Revisions record, @Param("example") RevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") Revisions record, @Param("example") RevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") Revisions record, @Param("example") RevisionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeySelective(Revisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeyWithBLOBs(Revisions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISIONS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKey(Revisions record);
}