package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.RevisionHist;
import q4s.tutorials.mybatis.annot.entity.RevisionHistExample;
import q4s.tutorials.mybatis.annot.entity.RevisionHistKey;

public interface RevisionHistMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(RevisionHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(RevisionHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(RevisionHistKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(RevisionHist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(RevisionHist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<RevisionHist> selectByExampleWithBLOBs(RevisionHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<RevisionHist> selectByExample(RevisionHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	RevisionHist selectByPrimaryKey(RevisionHistKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") RevisionHist record, @Param("example") RevisionHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") RevisionHist record, @Param("example") RevisionHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") RevisionHist record, @Param("example") RevisionHistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeySelective(RevisionHist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeyWithBLOBs(RevisionHist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table REVISION_HIST
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKey(RevisionHist record);
}