package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.Skills;
import q4s.tutorials.mybatis.annot.entity.SkillsExample;

public interface SkillsMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(SkillsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(SkillsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(Long skillId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(Skills record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(Skills record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<Skills> selectByExample(SkillsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	Skills selectByPrimaryKey(Long skillId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") Skills record, @Param("example") SkillsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") Skills record, @Param("example") SkillsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeySelective(Skills record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKILLS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKey(Skills record);
}