package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.Tags;
import q4s.tutorials.mybatis.annot.entity.TagsExample;

public interface TagsMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(TagsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(TagsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(String tagId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(Tags record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(Tags record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<Tags> selectByExample(TagsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") Tags record, @Param("example") TagsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TAGS
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") Tags record, @Param("example") TagsExample example);
}