package q4s.tutorials.mybatis.annot.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import q4s.tutorials.mybatis.RootInterface;
import q4s.tutorials.mybatis.annot.entity.TaskTypes;
import q4s.tutorials.mybatis.annot.entity.TaskTypesExample;

public interface TaskTypesMapper extends RootInterface {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	long countByExample(TaskTypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByExample(TaskTypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int deleteByPrimaryKey(Long typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insert(TaskTypes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int insertSelective(TaskTypes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	List<TaskTypes> selectByExample(TaskTypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	TaskTypes selectByPrimaryKey(Long typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExampleSelective(@Param("record") TaskTypes record, @Param("example") TaskTypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByExample(@Param("record") TaskTypes record, @Param("example") TaskTypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKeySelective(TaskTypes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TASK_TYPES
	 * @mbg.generated  Tue Jun 23 13:10:31 MSK 2020
	 */
	int updateByPrimaryKey(TaskTypes record);
}